### ISSUE TITLE
1.3.0 打开闪退

### ISSUE THREAD

**Issue by pinksheer** [GoldenHuaji/QScript#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.tsihen.qscript/me.tsihen.qscript.MainActivity}: android.view.InflateException: Binary XML file line #55: Binary XML file line #55: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2485)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5597)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
Caused by: android.view.InflateException: Binary XML file line #55: Binary XML file line #55: Error inflating class <unknown>
	at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at me.tsihen.qscript.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:2)
	at me.tsihen.qscript.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:1)
	at me.tsihen.qscript.MainActivity.onCreate(MainActivity.kt:2)
	at android.app.Activity.performCreate(Activity.java:6355)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #55: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:649)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:623)
	... 27 more
Caused by: android.content.res.Resources$NotFoundException: Resource "me.tsihen.qscript:drawable/bg_yellow_solid" (1f080067) is not a Drawable (color or path): TypedValue{t=0x1/d=0x1f080067 a=-1 r=0x1f080067}
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2646)
	at android.content.res.Resources.loadDrawable(Resources.java:2580)
	at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:398)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:872)
	at android.view.View.<init>(View.java:3963)
	at android.view.ViewGroup.<init>(ViewGroup.java:574)
	at android.widget.LinearLayout.<init>(LinearLayout.java:203)
	at android.widget.LinearLayout.<init>(LinearLayout.java:199)
	at android.widget.LinearLayout.<init>(LinearLayout.java:195)
	... 29 more

**Comment by GoldenHuaji** [comment]
是否安装了其他模块？

**Comment by pinksheer** [comment]
是的，我还安装了QN和QX
